### ISSUE TITLE
Setting an ideal rectangular voltage source with parameters

### ISSUE THREAD

**Issue by cmat21** [ra3xdh/qucs_s#256] opened 2023-04-06 02:30 UTC
Hello, could you help me to use parameters within the ideal rectangular voltage source. I attach an image with the results of a simulation comparing the configurations of the sources using parameters. I don't get the same results when I use parameter on "TH=pw" and the same goes for "th","tr","tf","tl". Please tell me if I am forgetting something to configure.
Thank you
![source](https://user-images.githubusercontent.com/70080894/230260935-21ddf101-4458-44f6-a55b-d8f3a023a4b6.PNG)
[Source_03.zip](https://github.com/ra3xdh/qucs_s/files/11165895/Source_03.zip)

**Comment by ra3xdh** [comment] 2023-04-06 18:49
The question about rectangular source was raised before several times. It is not a bug. See #249 for explanation. Qucs-S netlister calculates period as `PER=TL+TH` and assumes `TH=PW`. The blue source also ignores the variables, because the calculations cannot be applied for such case. This may be not matching with SPICE. I cannot correct these calculations because the backward compatibility with old Qucs circuits may be lost. Use full SPICE definition using the red source as shown in #249 if you need parametrized schematic.

**Comment by ra3xdh** [comment] 2023-04-06 18:50
Closing as duplicate of #249

**Closed by ra3xdh** 2023-04-06 18:50 UTC
