### ISSUE TITLE
Filenames with Decimal

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#319] opened 2023-10-05 02:13 UTC
Qucs allowed filenames with decimals but Qucs-S has an issue as shown. 

I know ngspice doesn't like filenames with spaces but I'm unsure about decimals.

![2023-10-04_220528](https://github.com/ra3xdh/qucs_s/assets/102838604/cca9a614-be80-46a9-817f-c1c4d479e0a5)

**Comment by ra3xdh** [comment] 2023-10-05 05:53
Hello Tom, I have recently discovered the same problem and added a fix. See #311 This fix will be available since the next release. I am wondering that this problem was hiding undiscovered for several years. Closing this as duplicate of #311

**Closed by ra3xdh** 2023-10-05 05:53 UTC
Labels: duplicate
