### ISSUE TITLE
Sweep of a subcircuit parameter

### ISSUE THREAD

**Issue by 0range0range** [ra3xdh/qucs_s#192] opened 2022-12-05 07:15 UTC
I have a problem with sweeping parameter of a subcircuit using Ngspice,

As described here: 
https://qucs-s-help.readthedocs.io/en/latest/ASim.html?highlight=parameter%20sweep#one-and-two-parameter-sweep-controlled-simulations
it is possible to do this using ngspice specifying parameter as @dev_name[param_name]

Here is the minimal working example with a subcircuit being a voltage divider.

Main circuit:
![image](https://user-images.githubusercontent.com/95714694/205573327-60200e01-15ca-4516-ba7f-71f8e6fa8a99.png)

Subcircuit:
![image](https://user-images.githubusercontent.com/95714694/205573425-209540e8-60ab-4e16-9ed9-a2d3226e1abb.png)

![image](https://user-images.githubusercontent.com/95714694/205574336-54ce32c8-d3e5-4367-81ae-b1ae293c3b4e.png)

I get the following after running simulation on a main circuit:
```
Ngspice started...
Error: no such device or model name volt_div1

```
And this error is repeated for all the parameter steps.

Am I doing something wrong and how can this be achieved?

[test2.txt](https://github.com/ra3xdh/qucs_s/files/10151420/test2.txt)
[divider_subcircuit.txt](https://github.com/ra3xdh/qucs_s/files/10151421/divider_subcircuit.txt)

Uploading schematic files as test file, since github does not accept .sch.

**Comment by ra3xdh** [comment] 2022-12-05 07:39
It is not a bug. The `@device[param]` syntax serves only for sweeping parameters of the modelcards `.MODEL`. It is not applicable for subcircuits. Furthermore it is not possible to directly sweep subcircuit parameters with Ngspice. Probably a new feature with global variable sweep may help you #189

**Comment by ra3xdh** [comment] 2023-02-03 14:09
Closing this. Let's see if the #189 will help. Otherwise the sweep of the subcircuit parameter is not possible with Ngspice.

**Closed by ra3xdh** 2023-02-03 14:09 UTC
Labels: question
