### ISSUE TITLE
Setting graph limits manually

### ISSUE THREAD

**Issue by 0range0range** [ra3xdh/qucs_s#250] opened 2023-03-24 10:35 UTC
1. When I try to change limits of the graph manually and previous automatic value is an integer, I am not able to type decimal separators. Neither `.`, not `e-`. I can only put comma, which is being ignored by Qucs-s.

2. Weirdly, if the cell already has a number with fractional part (either in normal or scientific form), then everything is working without problems.

3. Now if I erase, for example, `step` cell completely I can not input fractional numbers. Even though before I cleared it (assuming there was a number with fractional part) I could do it, as explained in 1,2.  Copy-paste of fractional number also does not work

**TODO** list from @ra3xdh 
- [x] Add explicit locale setting for every `QDoubleValidator`. It should not accept comma instead of dot.

![image](https://user-images.githubusercontent.com/95714694/227497363-ab6c34e0-b86a-4507-b8f9-ddfc2e9491bd.png)

**Comment by ra3xdh** [comment] 2023-03-24 14:11
What is your system locale? I tried to reproduce this issue with the `en_US` and `de_DE` locale but with no success. The `de_DE` locale begins to accept comma `,` as the delimiter but still accept dot `.`. But I believe the reported issue could take place. The `QDoubleValidator` class has the locate setting method `setLocale()` and the double number syntax may become locale dependent. It seems the validators require an explicit setting of the locale.

**Comment by ra3xdh** [comment] 2023-03-25 17:15
@0range0range , you may try the `current` branch with the latest commit. I have added explicit locale setting for `QDoubleValidator`. But I have tried different locale combination and still not able to reproduce this problem.

**Comment by ra3xdh** [comment] 2023-04-08 16:19
@0range0range Have you tried the `current` branch or setting `en_US` locale like this?
~~~
LANG=en_US qucs-s
~~~
What is your distribution and Qt version?

**Comment by ra3xdh** [comment] 2023-04-23 11:50
No further info regarding this issue. Still cannot reproduce it. Assume this was related to `QValidator` locale setting. Now all `QValidator` instances should be locale-independent. Closing this.

**Closed by ra3xdh** 2023-04-23 11:50 UTC
Labels: bug, qt5, qt6, cannot reproduce
