### ISSUE TITLE
The trail behind the model

### ISSUE THREAD

**Issue by SCP1715** [ra3xdh/qucs_s#229] opened 2023-02-22 11:06 UTC
I noticed that when you move the model around the workspace, it leaves a trail behind it. I found that this is caused by the model being drawn twice when moving
I was able to fix this by commenting out the first method call:

`selElem->paintScheme(Doc)`
in 
`void MouseActions::MMoveElement(Schematic *Doc, QMouseEvent *Event)`

**Comment by ra3xdh** [comment] 2023-02-22 11:12
It's strange but I also cannot reproduce this issue on my hardware. The device moving works as expected. What is your hardware, OS and Qt version?

**Comment by SCP1715** [comment] 2023-02-22 11:21
I noticed this on windows 7, Qt 5.14 and 5.8 
![1](https://user-images.githubusercontent.com/122429416/220605857-f190c0f4-e27e-474e-8f07-a46806616649.png)
![2](https://user-images.githubusercontent.com/122429416/220605860-72f486ef-d7cd-4727-b3d3-824210035260.png)
This is noticeable when you move the models very slowly or very quickly

**Comment by ra3xdh** [comment] 2023-02-22 11:23
Yes, I understood how to reproduce it now. It appears only if the device is moved very slowly.

**Comment by ra3xdh** [comment] 2023-09-26 13:41
The fixing of this issue may require the redesign the schematic rendering widget that is not considered in the near future. This issue is rare to appear during the normal operation and doesn't affect the application operation. Closing as won't fix.

**Closed** 2023-09-26 13:41 UTC
Labels: wontfix, qt5, qt6
