### ISSUE TITLE
Qucs-S generated log.txt does not match ngspice generated spice4qucs.log

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#218] opened 2023-02-15 00:30 UTC
When comparing "log" files generated by Qucs-S versus ngspice (DuSpice), I found log.txt generated by Qucs is missing critical info contained in the ngspice generated log file located in the ngspice.../bin folder.  It also has nonsensical error messages compared to the ngspice log file. It makes it difficult to diagnose what is wrong.  

![MOC3043M_TRAN sch](https://user-images.githubusercontent.com/102838604/218893977-4f4a0032-ad63-40da-8e71-85943daf0a2a.jpg)

![2023-02-14_192929](https://user-images.githubusercontent.com/102838604/218894288-91f332d8-bf2a-43eb-9ab8-4e1ff1849238.jpg)

![2023-02-14_192917](https://user-images.githubusercontent.com/102838604/218894268-daa490f7-fc9e-4b8f-909b-0120bb098dcc.jpg)

[Qucs_netlists.zip](https://github.com/ra3xdh/qucs_s/files/10738007/Qucs_netlists.zip)
[Qucs-ngspice_logs.zip](https://github.com/ra3xdh/qucs_s/files/10737958/Qucs-ngspice_logs.zip)
[ngspice_data_logs.zip](https://github.com/ra3xdh/qucs_s/files/10737946/ngspice_data_logs.zip)

**Comment by ra3xdh** [comment] 2023-02-15 07:08
There is no bug here. I have already explained you that Qucs-S doesn't generate log file by itself. It shows the log obtained from Ngspice as is. It doesn't hide any information. I launched Ngspice from the command line with your netlist and obtained exactly the same log as shown by Qucs-S. Qucs-S dosn't apply any Ngspice options to suppress the log output.  Your DuSpice installation may apply some hidden option to Ngspice that may cause the difference in logs. 

![image](https://user-images.githubusercontent.com/4920080/218956725-700c7a55-2654-476d-9cb6-b88350354f56.png)

**Comment by ra3xdh** [comment] 2023-02-15 07:15
Also I have explained you before that you are using `SpiceLibComp` device wrong. It is designed for direct placement on the schematic and assign the symbol from the `*.sym` file. It may cause `nested subcircuits` error if wrapped in subschematic. Use the `SpiceFile` device instead. The `nested subcircuit` error has gone with it. 

![image](https://user-images.githubusercontent.com/4920080/218958122-49915486-bddc-4277-aac7-adc377b25d6d.png)

**Comment by tomhajjar** [comment] 2023-02-15 13:48
If I'm not supposed to use SpiceLibComp to make a subcircuit, how do I specify a specific component, MOC3082 inside MOC308x.lib using SpiceFile?

![2023-02-15_084002](https://user-images.githubusercontent.com/102838604/219043732-9355a450-70c5-47a8-a89b-2fbf7a96b9f9.jpg)

![2023-02-15_084035](https://user-images.githubusercontent.com/102838604/219043747-f5649d88-45f8-460c-bd7d-88b2ad9ad77f.jpg)

[MOC3082M_TRAN.zip](https://github.com/ra3xdh/qucs_s/files/10743585/MOC3082M_TRAN.zip)

**Comment by ra3xdh** [comment] 2023-02-15 13:50
> If I'm not supposed to use SpiceLibComp to make a subcircuit, how do I specify a specific component, MOC3082 inside MOC308x.lib using SpiceFile?

Copy the models for each device into separate CIR file.

**Comment by tomhajjar** [comment] 2023-02-15 13:55
Yes obviously but I have been using SpiceLibComp this way for a long time and it generally works. Seems like a step backward.

**Comment by ra3xdh** [comment] 2023-02-15 14:01
> I have been using SpiceLibComp this way for a long time and it generally works

There is no warranty of proper operation if used inside a subcircuit. But for some cases it will work properly. Sometimes it may produce a nested subcircuit error. Also `SpiceLibComp` cannot produce a proper library entry because it still reference the library file using `.INCLUDE`. So it is not recommended if it is planned to generate the library using *Project->Create Library*

**Comment by tomhajjar** [comment] 2023-02-15 15:37
So I converted the files and no luck. ngspice does not like SpiceFile using the "new" MOC3082.cir 

The original MOC3082M.sch uses SpiceLibComp pointing to MOC3082 inside MOC308x.lib and it works

The new MOC3082.sch using SpiceFile and the new MOC3082.cir doesn't work

I created MOC3082_cir.sch using SpiceLibComp pointing to MOC3082 inside MOC3082.cir and it works

[MOC3082.zip](https://github.com/ra3xdh/qucs_s/files/10744673/MOC3082.zip)

**Comment by ra3xdh** [comment] 2023-02-15 15:48
It is again not a bug of Qucs-S or Ngspice. Your `MOC3082.cir` file is corrupt and contains unallowed unicode symbols. Fix this file first.
![image](https://user-images.githubusercontent.com/4920080/219078589-9c22333a-c195-4d00-b644-fdb04bf778c8.png)

**Comment by ra3xdh** [comment] 2023-02-15 15:55
After fixing the corrupted symbols and renaming MOC382 to MOC3082_sub everything works fine. Otherwise Ngspice reports `Duplicate subcircuits` error.
![image](https://user-images.githubusercontent.com/4920080/219080461-2ca59f2c-ee68-4ecc-8a8e-6d9a8343e4ce.png)
![image](https://user-images.githubusercontent.com/4920080/219080601-9988ac85-c5df-4914-834c-358c167d3ab6.png)

**Comment by tomhajjar** [comment] 2023-02-15 16:22
I cannot find the corrupted symbols. I used multiple text editors and cannot see them. Only thing I see is µ versus u

**Comment by ra3xdh** [comment] 2023-02-15 16:41
> Only thing I see is µ versus u

Yes, the µ symbol is not allowed for Ngspice. It can recognize only ASCII symbols, but not unicode.

**Comment by ra3xdh** [comment] 2023-02-15 16:42
I have ported MOC3082 to Ngspice syntax, so it works without setting `ltpsa` mode now. The model is below:

~~~
* MOC3082  I_trig=10mA
*  D+  D-  MT2  MT1
*
.subckt moc3082_sub 1 2 3 4
.PARAM Itrig=10m
.PARAM RH1=20k
.PARAM RH2=20k
.PARAM RH3=16.7k
Q1 vb1p vb1 4 0 NPN1
Q2 vb1 vb1p vd1 0 PNP1
R3 vb1 4 {RH2}
D1 1 2 DL
R1 ctrl10 4 1
C1 ctrl10 4 10u
R2 ctrl1 vb1 {RH1}
R4 vd1 vb1p {RH3}
B1 ctrl10 4 I=-500*I(D1)*3m/Itrig
R7 vb2p 4 {RH3}
R6 vd2 vb2 {RH2}
Q3 vb2p vb2 vd2 0 NPN1
Q4 vb2 vb2p 4 0 PNP1
D3 vd2 3 D1
D2 3 vd1 D1
R5 N001 vb2 {RH1}
E1 vd2 N001 ctrl1 4 -1
R34 3 4 100MEG
R12 ctrl1 4 1
B2 ctrl1 4 V=(V(ctrl10,4)>1.45 && abs(V(34)) < 12?2:0)
C2 ctrl1 4 1u
B3 34 0 I=-V(3,4)/1000
R13 34 0 1k
C3 34 0 .1u
.MODEL PNP1 PNP(Is=1e-15 BF=10 Cjc=10p Cje=20p Tf=0.1u Ise=1e-12)
.MODEL NPN1 NPN(Is=1e-15 BF=10 Cjc=10p Cje=20p Tf=0.1u Ise=1e-12)
.MODEL D1 D(Is=0.1u Rs=2 Cj0=50p)
.MODEL DL D(Is=1e-20 Rs=5)
.ends moc3082
~~~

**Comment by tomhajjar** [comment] 2023-02-15 17:04
Not working for me. I'm baffled.....

[MOC3082_sub.zip](https://github.com/ra3xdh/qucs_s/files/10745525/MOC3082_sub.zip)

**Comment by ra3xdh** [comment] 2023-02-15 17:08
The `SpiceFile` device provides a wrapper for the inner subcircuit. If inner subcircuit and outer subcircuit name is the same the Ngspice will show "Duplicate subcircuits" error. Rename the `MOC3082_sub.sch` to `MOC3082.sch` and the error will disappear.

**Comment by ra3xdh** [comment] 2023-02-17 05:19
Closing because cannot reproduce the log file issue. Discussion regarding the optocoupler devices is not related to log file and should continue in #213

**Closed by ra3xdh** 2023-02-17 05:19 UTC
Labels: question
