### ISSUE TITLE
Symbol Text Issue

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#873] opened 2024-07-27 00:25 UTC
The text font/size/position used in a subcircuit symbol still does not match the symbol once made into a library. The library symbol text is sub-optimal. I thought this was addressed in #765 & #777.

Compare TL494 Symbol in TL494.sch to the one in PWM_Controller.lib

![2024-07-26_201822](https://github.com/user-attachments/assets/862df87c-25ab-4b1d-a86a-0170f9a10e7f)

![2024-07-26_201747](https://github.com/user-attachments/assets/7833d200-6b48-4361-8cdd-4135bd791553)

[TL494.zip](https://github.com/user-attachments/files/16397558/TL494.zip)

**Comment by wawuwo** [comment] 2024-07-30 07:42
I believe I understand what is the cause of the problem, but I'm not so sure.

When the symbol is saved its elements are saved as paintings (a line, a rect, a text, etc.) and in that case texts have their sizes measured in points (pts). But texts as parts of a symbol have to have their sizes in pixels, so when a symbol is loaded the sizes in points are treated as sizes in pixels, hence the "scaling".

I'll try to come up with a fix.

**Comment by tomhajjar** [comment] 2024-08-22 14:58
Any progress on this? The issue didn't exist in March when I did the attached project. Any symbol with text looks OK when making and editing the symbol but looks bad when the symbol is placed on a schematic.

![2024-08-21_215119](https://github.com/user-attachments/assets/87519162-00a8-4410-81e7-f94753270627)
![2024-08-21_215103](https://github.com/user-attachments/assets/56b37714-469f-41f9-96aa-751411e87550)

[Digital_Analog_Mixed_prj.zip](https://github.com/user-attachments/files/16713718/Digital_Analog_Mixed_prj.zip)

**Comment by wawuwo** [comment] 2024-08-25 12:19
@tomhajjar hi! Check the linked PR please, it should fix the problem. I've added explicit conversion from points to pixels, when symbol is read by component. But there is drawback with this approach: conversion from points to pixels gives different results on different displays because different pixel density. So it's more like a workaround than a proper fix.

**Comment by tomhajjar** [comment] 2024-08-25 13:51
Will do when the latest Windows nightly is released

**Comment by ra3xdh** [comment] 2024-08-25 14:57
Fixed by #912.

**Closed** 2024-08-25 14:56 UTC
Labels: bug

**Comment by tomhajjar** [comment] 2024-08-26 20:46
I checked a number of old projects and the update is a big improvement.
