### ISSUE TITLE
Xanalogue Library Graphics

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#308] opened 2023-09-19 03:25 UTC
Four Xanalogue Library devices display garbage for the device graphic that is in the middle of the schematic symbol outline. 

However if I cut and paste the symbol info into a schematic, the graphic is correct.

![2023-09-18_225852](https://github.com/ra3xdh/qucs_s/assets/102838604/720d2caa-54fb-4657-bea9-19b1c78285b6)
![2023-09-18_232223](https://github.com/ra3xdh/qucs_s/assets/102838604/1376b958-27f7-49c9-b6f9-b28f44974d29)
[Symbol_creation_prj.zip](https://github.com/ra3xdh/qucs_s/files/12655529/Symbol_creation_prj.zip)

**Comment by ra3xdh** [comment] 2023-09-19 12:56
I cannot reproduce the issue with symbols using Linux platform. It seems Windows-only issue. Need to make more debugging to fix this.
![image](https://github.com/ra3xdh/qucs_s/assets/4920080/8c99233a-c795-4fe8-b3b0-c399893af80b)

**Comment by tomhajjar** [comment] 2023-09-22 02:12
I have some more info. 

The Xanalogue.lib component XA_CSWO uses "~" but the "Show model" prevue displays garbage instead of "~".

The Xanalogue.lib components XA_int_DE and XA_int_SE use "?" instead of an integral symbol. The "Show model" prevue displays garbage instead of "?". 

I'm fixing the graphics issues by using Arc's and Lines instead of "~" and "?". I'm also making the graphics consistent and cleaner. It will be a few days before I'm done.

![2023-09-21_221054](https://github.com/ra3xdh/qucs_s/assets/102838604/af14d943-350a-4909-928d-22cff6cd4d7e)

![2023-09-21_221157](https://github.com/ra3xdh/qucs_s/assets/102838604/4f8127ce-8ace-4ef0-891d-6fb3e2b73c49)

**Comment by ra3xdh** [comment] 2023-09-22 05:41
@tomhajjar This issue should be fixed in C++ level. I guess the unicode support should be switched somewhere explicitly for Windows. @zergud  will provide debugging in the next week.

**Comment by tomhajjar** [comment] 2023-09-25 21:41
Still puzzled how an ASCII "?" can display an integral symbol...

**Closed** 2023-09-27 14:01 UTC
Labels: bug, windows

**Comment by ra3xdh** [comment] 2023-09-27 14:03
Fixed by #316. Closing as completed. The correction in the library is not needed. The fix will be available since the next release.
