### ISSUE TITLE
No libraries install by default

### ISSUE THREAD

**Issue by tomasApo** [ra3xdh/qucs_s#490] opened 2024-01-23 22:03 UTC
Hi I have a fresh install from this qucs repository but it is not coming with any system libraries. Although I do have components through the components tab. 
![image](https://github.com/ra3xdh/qucs_s/assets/75183079/af880cee-559a-4751-9258-418db3af2e07)
![image](https://github.com/ra3xdh/qucs_s/assets/75183079/345a9e90-b1ae-4a13-9f6b-acac803652e8)

**Any ideas or ways to solve this?**

**Comment by tomhajjar** [comment] 2024-01-24 02:03
What file did you use? Link?

https://ra3xdh.github.io/

**Comment by ra3xdh** [comment] 2024-01-24 05:37
@tomasApo The both RPM/DEB packages distributed from the OBS repository contain libraries. Use this link for install https://software.opensuse.org/download.html?project=home%3Ara3xdh&package=qucs-s WIndows installer also contain the libraries. I cannot reproduce the missing libraries issue n a fresh installation.

If you are using the package from Fedora main repository, you must install the libraries yourself: https://packages.fedoraproject.org/pkgs/qucs-s/qucs-s/ The Fedora team keeps libraries in a separate package: https://packages.fedoraproject.org/pkgs/qucs-s/qucs-s-library

**Comment by ra3xdh** [comment] 2024-01-29 17:20
No further information provided. Assume this was Fedora package installation that requires a separate library package. Closing this ticket.

**Closed by ra3xdh** 2024-01-29 17:20 UTC
Labels: question, packaging
