### ISSUE TITLE
Error: Unknown option: -b

### ISSUE THREAD

**Issue by ouening** [ra3xdh/qucs_s#24] opened 2019-04-24 10:46 UTC
Some examples can't run correctly!
I tried "Amp_Baseband_Low-noise.sch" with simulator "qucstor", the error like title shows happened: `Error: Unknown option: -b` ，and Itried simulator “ngspice” ，I got another different error:
```
Ngspice started...
ERROR: Cannot load subcircuit "Vnoise.sch".
Circuit: * qucs 0.0.21 d:/applications/qucs-s/share/qucs-s/examples/amp_baseband_low-noise.sch

Note: No ".plot", ".print", or ".fourier" lines; no simulations run
```

But I can run it correctly using "qucs-0.0.19-win32-mingw482-asco-freehdl-adms"，is it a bug in qucs-S?

**Comment by ra3xdh** [comment] 2022-02-19 11:43
Cannot reproduce with the new version. Closing.

**Closed by ra3xdh** 2022-02-19 11:43 UTC
