### ISSUE TITLE
Getting Simulations to work using OSDI files

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#1083] opened 2024-11-21 15:47 UTC
Not having luck getting @dwarning Verilog examples to work using OSDI files. Can you spot what I'm doing wrong?

I made multiple netlists as well as use dwarning's test netlists and still no luck.

I hope it's easier to use the OSDI files instead trying to build/link/compile the Verilog files. I deleted all the MS SW after Openvaf became unsupported.

![2024-11-21_073458](https://github.com/user-attachments/assets/cc74dfaf-a39b-46e4-ae30-b3caef8b1acd)
![2024-11-21_080305](https://github.com/user-attachments/assets/cc57ac9d-8959-41c4-aa3a-cfb0cfaa21b1)
![2024-11-21_074957](https://github.com/user-attachments/assets/a7779938-6a06-4bab-85d5-5601d45ce0c0)

[EKV3_osdi_test_prj.zip](https://github.com/user-attachments/files/17848425/EKV3_osdi_test_prj.zip)

**Comment by ra3xdh** [comment] 2024-11-21 16:26
There is something wrong with the provided OSDI file. It doesn't load on my machine too (Ngspice-43 using Arch(Manjaro) Linux). The Ngspice gives the following error:

~~~
Error: Library /home/vvk/.qucs/EKV3_osdi_test_prj/ekv3.osdi couldn't be loaded!
Error opening osdi lib "/home/vvk/.qucs/EKV3_osdi_test_prj/ekv3.osdi": /home/vvk/.qucs/EKV3_osdi_test_prj/ekv3.osdi: invalid ELF header
Error: Library /home/vvk/.qucs/EKV3_osdi_test_prj/ekv3.osdi couldn't be loaded!
~~~

This is surely not Qucs-S error. You should try to compile the OSDI file locally.  Closing this issue as "not a bug" because this is not related to Qucs-S GUI. I am not considering the extension of Verilog-A/OSDI support in the near future.

**Closed by ra3xdh** 2024-11-21 16:26 UTC

**Comment by dwarning** [comment] 2024-11-21 21:34
@ra3xdh @tomhajjar 
For me it is interesting from which source your osdi files stem. Are they self compiled or from my [repository ](https://github.com/dwarning/VA-Models). Which compiler was used?

**Comment by tomhajjar** [comment] 2024-11-21 21:47
I used your repository for the osdi files. I deleted all the MS SW required Openvaf became unsupported so I cannot create them anymore. My only goal is to create more test projects for new users.

**Comment by ra3xdh** [comment] 2024-11-23 06:12
> My only goal is to create more test projects for new users.

The tunnel diode project from #411 is sufficient. The Verilog-A support is required only for a few academic users. I think the distribution of binary OSDI files is not a good practice.  The OpenVAF still be developed by another developer in this fork: https://github.com/arpadbuermen/OpenVAF It's need to check if everything compiles using this version.

**Comment by tomhajjar** [comment] 2024-11-23 17:33
I redid the Tunnel diode project. I made two projects to make it easier for new users.

I had to reload a number of MS packages plus downloaded the latest openvaf. 
https://fides.fe.uni-lj.si/openvaf/download/

![2024-11-23_093105](https://github.com/user-attachments/assets/0f6cbcaf-e43a-461d-92a1-c586aedeb525)

[Verilog-A_Tunnel_projects.zip](https://github.com/user-attachments/files/17881988/Verilog-A_Tunnel_projects.zip)

**Comment by tomhajjar** [comment] 2024-11-23 21:35
@ra3xdh 

One persistent issue is Qucs-S will display ngspice errors that don't happen if the netlist is sent via DuSpice to ngspice.

In the attached project the following occurs: 

Ngspice started...
Error opening osdi lib "HICUML2V3.osdi": No such file or directory!
Error: Library HICUML2V3.osdi couldn't be loaded!

The "such file or directory" Error has happened many times and goes away when I use DuSpice to send netlist to ngspice. Attached is the project and two netlists.

HICUML2V3_ic_ib.cir is the raw unedited netlist
HICUML2V3_ic_ib_edit.cir is edited to get a plot

![2024-11-23_160604](https://github.com/user-attachments/assets/127d5cb2-2323-4245-9496-f178c4b0a9e1)
![2024-11-23_161920](https://github.com/user-attachments/assets/a967aa5d-a7c6-4c4f-8fea-d87f53fade00)

[HICUML2V3_osdi_prj.zip](https://github.com/user-attachments/files/17882621/HICUML2V3_osdi_prj.zip)

**Comment by Kreijstal** [comment] 2024-12-01 19:30
> I redid the Tunnel diode project. I made two projects to make it easier for new users. Traditional that makes a Verilog library device and odsi only including making a sub-circuit with a schematic symbol.
> 
> I had to reload a number of MS packages plus downloaded the latest openvaf. https://fides.fe.uni-lj.si/openvaf/download/
> 
> ![2024-11-23_093105](https://private-user-images.githubusercontent.com/102838604/389215626-0f6cbcaf-e43a-461d-92a1-c586aedeb525.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwODE1ODIsIm5iZiI6MTczMzA4MTI4MiwicGF0aCI6Ii8xMDI4Mzg2MDQvMzg5MjE1NjI2LTBmNmNiY2FmLWU0M2EtNDYxZC05MmExLWM1ODZhZWRlYjUyNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxOTI4MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjY0ZDI5YWUxNjIwNjJjZjdlN2UzOTZmODM5YTMyMmRlMzY3ZDE0ZjAwNTgzMjdiNTJkYzc2ZjY3MGRkNThjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xc5phQeBVI4iK6rAeiaiDsdhO01bL_mqGcKjKVVccMw)
> 
> [Verilog-A_Tunnel_projects.zip](https://github.com/user-attachments/files/17881988/Verilog-A_Tunnel_projects.zip)

did you try this openvaf-reloaded pull request, you don't need msvc
https://github.com/arpadbuermen/OpenVAF/pull/9

**Comment by Kreijstal** [comment] 2024-12-01 22:41
> Where is this "new" OpenVAF.exe for Windows?
> 
> I would need to test it on a different Windows PC that doesn't have all the MS tools installed.

You don't need ms tools, you can just use msys2 toolchain without installing any ms tools, you can run this msys2 toolchain completely portably, no installation neeeded.

**Comment by tomhajjar** [comment] 2024-12-02 04:04
So this won't be a "portable" single file like the present version of OpenVAF.exe for Windows?

**Comment by Kreijstal** [comment] 2024-12-02 06:09
> So this won't be a "portable" single file like the present version of OpenVAF.exe for Windows?

It requires only 1 file which is llvm dll the rest should be available on Windows
ntldd OpenVAF/target/release/openvaf-r.exe
        bcrypt.dll => C:\Windows\SYSTEM32\bcrypt.dll (0x00000211142a0000)
        ntdll.dll => C:\Windows\SYSTEM32\ntdll.dll (0x0000021122240000)
        shell32.dll => C:\Windows\SYSTEM32\shell32.dll (0x0000021122240000)
        userenv.dll => C:\Windows\SYSTEM32\USERENV.dll (0x0000021122e20000)
        ws2_32.dll => C:\Windows\SYSTEM32\WS2_32.dll (0x0000021122f90000)
        ADVAPI32.dll => C:\Windows\SYSTEM32\ADVAPI32.dll (0x0000021122cf0000)
        KERNEL32.dll => C:\Windows\SYSTEM32\KERNEL32.dll (0x0000021122cf0000)
        libLLVM-19.dll => E:\msys64\ucrt64\bin\libLLVM-19.dll (0x00000211239d0000)
        ole32.dll => C:\Windows\SYSTEM32\ole32.dll (0x0000021122b40000)
        OLEAUT32.dll => C:\Windows\SYSTEM32\OLEAUT32.dll (0x0000021123610000)
        bcryptprimitives.dll => C:\Windows\SYSTEM32\bcryptPrimitives.dll (0x0000021122240000)

**Comment by Kreijstal** [comment] 2024-12-02 06:22
> > So this won't be a "portable" single file like the present version of OpenVAF.exe for Windows?
> 
> It requires only 1 file which is llvm dll the rest should be available on Windows ntldd OpenVAF/target/release/openvaf-r.exe bcrypt.dll => C:\Windows\SYSTEM32\bcrypt.dll (0x00000211142a0000) ntdll.dll => C:\Windows\SYSTEM32\ntdll.dll (0x0000021122240000) shell32.dll => C:\Windows\SYSTEM32\shell32.dll (0x0000021122240000) userenv.dll => C:\Windows\SYSTEM32\USERENV.dll (0x0000021122e20000) ws2_32.dll => C:\Windows\SYSTEM32\WS2_32.dll (0x0000021122f90000) ADVAPI32.dll => C:\Windows\SYSTEM32\ADVAPI32.dll (0x0000021122cf0000) KERNEL32.dll => C:\Windows\SYSTEM32\KERNEL32.dll (0x0000021122cf0000) libLLVM-19.dll => E:\msys64\ucrt64\bin\libLLVM-19.dll (0x00000211239d0000) ole32.dll => C:\Windows\SYSTEM32\ole32.dll (0x0000021122b40000) OLEAUT32.dll => C:\Windows\SYSTEM32\OLEAUT32.dll (0x0000021123610000) bcryptprimitives.dll => C:\Windows\SYSTEM32\bcryptPrimitives.dll (0x0000021122240000)

So strictly speaking no it's not compiled statically, in practice if you need to move it somewhere, just cooy the binary and the dll and place it on the same directory

**Comment by dwarning** [comment] 2024-12-03 07:05
I got 18.1.8.1from first pacman cmd. Switching to ci branch made the job.
General remark: Switching to newest llvm version brings not really advantage under users point of view.

**Comment by Kreijstal** [comment] 2024-12-03 07:36
> I got 18.1.8.1from first pacman cmd. Switching to ci branch made the job. General remark: Switching to newest llvm version brings not really advantage under users point of view.

that is okay, warning whenever you do `pacman -Syu` you will "upgrade" all of your msys2 packages (this will delete your shared library llvm18 and replace it with llvm19), so you will get llvm19 instead, this makes openvaf-r not run anymore (since at compile time it was linked to llvm18), if you try to compile again, it will not work, I thought it was a bug, but you will have to do 'cargo clean', and compile again. I thought they were incompatible versions, but it turns out, it was just rust cache acting.
