### ISSUE TITLE
Xyce pametric plot

### ISSUE THREAD

**Issue by dwarning** [ra3xdh/qucs_s#691] opened 2024-04-15 06:00 UTC
The problem is similar like #161 but seems not solved yet.
I try to make an CV plot with Xyce:

![xyce_plot](https://github.com/ra3xdh/qucs_s/assets/18441932/a68ec658-9d0c-448d-b2e7-4244edd73422)

The resulting data file (attached) looks very well and is plotable with gnuplot.
[nmos_cgs_vgs_xyce_script.txt](https://github.com/ra3xdh/qucs_s/files/14974626/nmos_cgs_vgs_xyce_script.txt)

How I can get the curve into Qucs-s?

**Comment by ra3xdh** [comment] 2024-04-15 06:09
This is as the same as #161 You have a set of 1x1 point plots, but not as a smooth plot. I am aware about this problem and there is no workaround without extension of XML dataset format. Qucs plotting engine cannot understand that a set of 1x1 plots is a smooth curve. You may set *Style: Stars* in the diagram properties dialog and you will see the data points.

**Comment by ra3xdh** [comment] 2024-04-15 06:10
Closing as duplicate of #161

**Closed by ra3xdh** 2024-04-15 06:10 UTC
Labels: duplicate, xyce
