### ISSUE TITLE
Bad themes support

### ISSUE THREAD

**Issue by jorgemrisco** [ra3xdh/qucs_s#69] opened 2021-09-04 18:32 UTC
Sometimes text and icons are barely readable depending on the theme. It'd be nice to have a "default Qucs-s color scheme" option so we don't have to change our global themes to use this application.

I've tested it with Manjaro's dark color schemes and it is really not readable, I'll just stick to using LTSPice running through wine because of that;

Screenshots:
1. Using the `Breath2 2021 Dark`color scheme
![image](https://user-images.githubusercontent.com/61189874/132104563-87e217ec-dcd7-4a52-84fa-249b635b94f0.png)

2.  Using `Breath 2`
![image](https://user-images.githubusercontent.com/61189874/132104578-630d581d-2a23-43a0-8d29-3a93dc10eac1.png)

[Here's the link to another user with a similar complaint](https://github.com/ra3xdh/qucs_s/issues/66)

**Comment by ra3xdh** [comment] 2022-02-14 16:36
duplicate of #66

**Closed by ra3xdh** 2022-02-14 16:36 UTC
