### ISSUE TITLE
Dual monitor initial size wrong

### ISSUE THREAD

**Issue by dsm** [ra3xdh/qucs_s#185] opened 2022-11-11 22:52 UTC
Initial launch size of the app cover two monitor maybe change the initial app size calculation

**Comment by ra3xdh** [comment] 2022-11-25 16:50
I cannot reproduce this issue using the Kubuntu 22.04+KDE5.92 The Qucs-S window positioned correctly on the main monitor. Seems to be WM-dependent.

**Comment by ra3xdh** [comment] 2023-04-23 11:53
I have tried different OS and hardware and still cannot reproduce this. Closing as cannot reproduce.

**Closed by ra3xdh** 2023-04-23 11:53 UTC
Labels: cannot reproduce
