### ISSUE TITLE
TL071 in SpiceOpamp doesn't work

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#1068] opened 2024-11-17 15:47 UTC
Not sure how it happened but the TL071 by Nazar Shtybel in SpiceOpamp doesn't work in ngspice. The model generates many ngspice warnings and generates large errors when the feedback resistor values are >1k. For R=10k the simulation is totally wrong. I will check if he updated the model.

I have many other models for the TL071 as well as other devices. SpiceOpamp could use an update... 

![2024-11-17_102825](https://github.com/user-attachments/assets/2a2a4dbb-7d9e-4d05-9852-8fc659bbd771)
![2024-11-17_102659](https://github.com/user-attachments/assets/af393954-ed08-4421-84e8-1e14a5ff2be0)

[OpAmp_Library_Test_prj.zip](https://github.com/user-attachments/files/17791399/OpAmp_Library_Test_prj.zip)
[OpAmp_Spice_Models_prj.zip](https://github.com/user-attachments/files/17791157/OpAmp_Spice_Models_prj.zip)

**Comment by ra3xdh** [comment] 2024-11-17 15:53
The model is not damaged and works as expected. The warnings about `T_ABS` parameters of diodes may be ignored. I will clean the model in the library.

![image](https://github.com/user-attachments/assets/37090ba3-cf26-4425-8041-bb64068d4221)

**Comment by tomhajjar** [comment] 2024-11-17 15:57
Try R1/R2=10k

**Comment by ra3xdh** [comment] 2024-11-17 17:00
Everything works as expected with 10k/10k. The model is not broken. I am using no compatibility mode. 

![image](https://github.com/user-attachments/assets/3e021002-95d7-401f-afe4-3709afb2aeb6)

**Comment by ra3xdh** [comment] 2024-11-17 17:02
10kHz source also works as expected.

**Comment by tomhajjar** [comment] 2024-11-17 17:04
I'm not sure what is going on. With R1/R2=100k, output is shifted by +6 volts...

![2024-11-17_115843](https://github.com/user-attachments/assets/eade88d7-d8bc-42eb-892e-18cd22c25521)

[TL071_Non_Inverter.zip](https://github.com/user-attachments/files/17791614/TL071_Non_Inverter.zip)

**Comment by tomhajjar** [comment] 2024-11-17 17:16
I used ngspice 38 and the issue is gone...

I will try to find what rev "broke" the model...

![2024-11-17_121621](https://github.com/user-attachments/assets/f3c2d68a-5ea8-4c7d-8704-c189f594b7f2)

**Comment by ivandi69** [comment] 2024-11-17 21:18
I can reproduce it with the latest ngspice from git and it is most likely caused by ngspice commit [a43c6f4916ef68029e7c777bd1485cc87609751d](https://sourceforge.net/p/ngspice/ngspice/ci/a43c6f4916ef68029e7c777bd1485cc87609751d)

Note these warnings about resistor value too small:
.SUBCKT TL071_SN  1 2 3 4 5
...
R4 6 0 1E-12 TC=130e-2
R19 0 32 6E-9
R20 0 34 6E-9
![image](https://github.com/user-attachments/assets/f079f55a-72a1-401b-8a4a-4dccce122e2e)

**Comment by tomhajjar** [comment] 2024-11-17 21:40
Hard to understand the reasoning for those 3 resistors are in the netlist. All provide a path to "0" for sources. Author uses the same scheme in his other Spice models like NE5534..etc.

I used his Spice models because they modeled Vcc/Vee currents which was important for audio power amplifiers with OpAmps in a Booster/Bootstrap configuration.

**Comment by tomhajjar** [comment] 2024-11-17 22:20
Holger says...

"I have uploaded a fix to development branch pre-master-44."

**Comment by ivandi69** [comment] 2024-11-17 22:58
RESMIN has been changed to 1E-12. So there is still one warning, but it seems to work as expected:
![image](https://github.com/user-attachments/assets/9f2fb505-722c-441c-9b30-d1a16bed6a0b)

**Comment by tomhajjar** [comment] 2024-11-17 23:16
There is no reason to have resistor values that small in the model especially since the Tempco parameters will be removed.

**Comment by ra3xdh** [comment] 2024-11-18 06:28
The problem was on Ngspice side. Closing this.

**Closed by ra3xdh** 2024-11-18 06:28 UTC
Labels: not a bug
