### ISSUE TITLE
Wrong Github download links of Qucs-S Windows installer and Windows portable package

### ISSUE THREAD

**Issue by 3813127458** [ra3xdh/qucs_s#621] opened 2024-02-29 05:52 UTC
The download links for the Qucs-S Windows installer and Windows portable package do not work:

![image](https://github.com/ra3xdh/qucs_s/assets/75557552/02cb8d49-b6e8-4821-b635-8a4edb3e4e11)

![image](https://github.com/ra3xdh/qucs_s/assets/75557552/39cde393-1f27-4d26-bf85-2acc48902d57)

![image](https://github.com/ra3xdh/qucs_s/assets/75557552/e65d46ec-6b0e-4f13-b9ef-fba38fbd50c5)

**Comment by tomhajjar** [comment] 2024-02-29 17:20
https://github.com/ra3xdh/qucs_s/releases/tag/24.1.0

**Comment by tomhajjar** [comment] 2024-02-29 17:28
Also the Windows install instruction at bottom of the page are not necessary and limit having multiple versions of ngspice/xyce spice as well. 

When debugging issues I have to confirm the problem isn't caused by the latest Qucs-S or ngspice version.

![2024-02-29_122709](https://github.com/ra3xdh/qucs_s/assets/102838604/7e5dabd3-27db-4f31-b670-418562dc06c4)
![2024-02-29_122647](https://github.com/ra3xdh/qucs_s/assets/102838604/52dc9867-8ab3-470d-9a0f-58081d1dd773)

**Comment by ra3xdh** [comment] 2024-03-01 05:26
I have fixed the package file names. Closing.

**Closed by ra3xdh** 2024-03-01 05:26 UTC
Labels: packaging
