### ISSUE TITLE
OP annotation with ngspice

### ISSUE THREAD

**Issue by dwarning** [ra3xdh/qucs_s#389] opened 2023-11-29 16:17 UTC
Is it possible to show the results of an OP analysis with ngspice?

If I make only dc analysis the was no op statement in netlist so in schematic only 0 stands in schematic:
![Bildschirmfoto vom 2023-11-29 17-08-56](https://github.com/ra3xdh/qucs_s/assets/18441932/2b513765-13d5-41db-be95-d5ad28dbb084)

Log file is complaining of missing model.
If I use the Nutmeg script block analysis is running and print all too but no annotation.

**Comment by ra3xdh** [comment] 2023-11-29 16:21
It is a known issue. This feature is not supported. SaveOP has no effect. See #124 I can suggest only to use F8 or 1 point DC sweep with table output. Zero output on the show circuit is not related to applied simulations. There is something wrong in the model itself. Look in the logs (press F5)

**Comment by ra3xdh** [comment] 2023-11-29 16:21
Closing as duplicate of #124

**Closed** 2023-11-29 16:24 UTC
Labels: duplicate
