### ISSUE TITLE
Opto-Coupler, Isolator, Triac Library

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#213] opened 2023-02-10 16:40 UTC
I'm working on a new Opto-Coupler, Opto-Isolator and Opto-Triac Library but I'm having problems getting Spice models that work under LTspice to work under ngspice. 

The first device I'm working on is a Photovoltaic Isolator or PVI. They have been around for decades with modern versions having much faster response time.  The most popular device is an Infineon PVI5050N. Unfortunately the factory model is unavailable and my attempts at creating a fully working version have failed. 

My next choices are the Vishay VOM1271 and Avago ACPL-K30T. 

VOM1271.cir created by the late LTspice contributor Jim Thompson, has been extensively tested under LTspice.

VOM1271.cir doesn't work under ngspice even using LTspice compatibility mode. 

Vishay supplied VOM1271T.cir doesn't work for LTspice or ngspice. 

Avago supplied ACPL-K30T.cir works under LTspice but give erroneous data under ngspice using LTspice compatibility mode. 

- [x] Rewrite LTspice models so it will operated with Ngspice without setting `ltps` mode
- [x] Create optocoupler devices library

![VOM1271_TRAN_Thompson](https://user-images.githubusercontent.com/102838604/218146376-bd265848-c02c-4c31-8572-921d12fbb3e5.jpg)

![VOM1271_DC_Thompson](https://user-images.githubusercontent.com/102838604/218146354-aa5b426e-e6a6-412a-8272-d4ae238483cd.jpg)

![ACPL-K30T_DC](https://user-images.githubusercontent.com/102838604/218147146-e1952e72-e1e0-4a9e-b860-a4e2162178eb.jpg)

![ACPL-K30T_TRAN](https://user-images.githubusercontent.com/102838604/218147165-24b5222a-2e0e-4cf7-9650-8495be68a85f.jpg)

![ACPL-K30T_DC_Qucs](https://user-images.githubusercontent.com/102838604/218146423-0724014e-3176-43c4-9fd6-f5cbd147e168.jpg)

![ACPL-K30T_TRAN_Qucs](https://user-images.githubusercontent.com/102838604/218146443-f41ecf9e-4ba3-4e72-9082-3ad8dcdb964d.jpg)

[Photo_Voltaic_Isolators_prj.zip](https://github.com/ra3xdh/qucs_s/files/10709449/Photo_Voltaic_Isolators_prj.zip)

**Comment by tomhajjar** [comment] 2023-02-10 22:20
First cut at MOC3043M Opto Triac. Works in LTspice but not ngspice. Looking at other spice models.

![MOC3043M_trigger](https://user-images.githubusercontent.com/102838604/218209477-846b56c1-17c7-4770-8e5b-ca1568c15e07.jpg)

[Opto Triac_prj.zip](https://github.com/ra3xdh/qucs_s/files/10711582/Opto.Triac_prj.zip)

**Comment by ra3xdh** [comment] 2023-02-11 15:37
> OnSemi MOC3043M Opto Triac works in LTspice but not ngspice

It seems the LTSpice compatibility mode in Ngspice is not fully implemented. At first I corrected subcircuit to use SpiceFile device instead of SpiceLibComp. The output of the Ngspice became more verbose. It reports error in the `IF` statement in the netlists and doesn't accept `VSWITCH` model. After I set `ngbehavior=ltpsa` the schematic starts to work, but the result is wrong. I suspect this model requires to be rewritten to work with Nsgpce.

**Comment by tomhajjar** [comment] 2023-02-12 01:37
I ran into an issue with the BRT22x Opto Triac simulations. I found a typo in BRT22H.sch. It points to the model BRT22M.cir. I then renamed it to BRT22M.sch and the simulation fails. I then made a "fresh" BRT22H.sch also pointing to the model BRT22M.cir and it fails. I tried every combination of making fresh schematics and I could not get the simulations to work. I compared all models and schematics with a file comparison tool and cannot find anything that would cause issues.  Only the original files BRT22H.sch and BRT22H_TRAN.sch I sent "work". 

As a side note, the BRT22x.lib spice models have 6 pins with two unused pins having the same name, "NC". They also have two "dummy" components C1and R4 connected to NC and 0. Qucs/ngspice wouldn't work unless I depleted the two "NC" pins. I named the models BRT22x.cir. The modified models worked in LTspice.

.SUBCKT BRT22M A C NC MT2 NC MT1
X1       MT2 GATE MT1 BRT22M_tr
D1      10 C Demit
V3      11 10 0Vdc
R3       A 11  1u TC=0,0
R4	   0 NC 1MEG
C1	   0 NC 1u

![BRT22H_sch](https://user-images.githubusercontent.com/102838604/218288228-820831f5-2918-424d-8997-54683d1d6ffb.jpg)

![BRT22H_trigger_Qucs](https://user-images.githubusercontent.com/102838604/218288233-c518a9e1-323f-4dce-8eee-b6703a5611e2.jpg)

![BRT22M_sch](https://user-images.githubusercontent.com/102838604/218288236-5cbe3fd3-adf1-43bd-b268-f4e48a5807a2.jpg)

![BRT22M_trigger_Qucs](https://user-images.githubusercontent.com/102838604/218288239-dd37fdba-018a-48a1-90e9-187656e83cbd.jpg)

[BRT22x_prj.zip](https://github.com/ra3xdh/qucs_s/files/10715070/BRT22x_prj.zip)

**Comment by tomhajjar** [comment] 2023-02-14 15:44
Vadim

Can you confirm if the issue above is a bug?

**Comment by ra3xdh** [comment] 2023-02-14 16:54
The problem with NC node is not a bug. It is a floating node that has no current and may cause a convergence issue with Ngspice. LTspice may automatically add parasitic from floating node to the ground, but Ngspice has no such feature.

Regarding the problem with path to the model file I cannot reproduce this issue. Probably there is something related to the relative search paths.

**Comment by tomhajjar** [comment] 2023-02-14 22:03
There is something wrong with Qucs-S. See the logs (renamed for clarity). 

The two netlists generated by Qucs (also renamed for clarity) work if I use DuSpice as the GUI. 

[Qucs_netlist_logs.zip](https://github.com/ra3xdh/qucs_s/files/10737155/Qucs_netlist_logs.zip)
[Qucs_netlists.zip](https://github.com/ra3xdh/qucs_s/files/10737154/Qucs_netlists.zip)
[ngspice_data_logs.zip](https://github.com/ra3xdh/qucs_s/files/10737163/ngspice_data_logs.zip)

**Comment by tomhajjar** [comment] 2023-02-15 01:47
I've given up on the OnSemi MOC3043M LTspice model.

An OnSemi MOC3082M LTspice model from the same source (https://groups.io/g/LTspice) seems to work OK. 

[MOC3082M_Opto_Triac.zip](https://github.com/ra3xdh/qucs_s/files/10738428/MOC3082M_Opto_Triac.zip)

**Comment by ra3xdh** [comment] 2023-02-15 05:35
> I've given up on the OnSemi MOC3043M LTspice model.

I have pointed above that LTSpice compatibility mode is not 100% LTSpice compatible. The most probably the problem is in default diode model that is used by MOC3043. It's unknown which parameters has the default diode and NPN devices in LTspice. By default model I mean the following usage `.MODEL D D`

**Comment by tomhajjar** [comment] 2023-02-15 19:10
First cut at an NPN output opto-isolator. 

4N25.cir is a model from the 90s and seems to work OK. More complicated than ones from LTspice.

4N35.cir from Vishay using my mods is not working. 4N35.lib is original. 

[4N25-35.zip](https://github.com/ra3xdh/qucs_s/files/10746471/4N25-35.zip)

**Comment by ra3xdh** [comment] 2023-02-16 06:54
4N35 contains model contains table-dependent source that is not supported by Ngspice. It is unclear how to modify it.

**Comment by tomhajjar** [comment] 2023-02-16 17:10
I found another Opto Isolator that uses the same model "architecture" that many in the LTspice forum use, MOC207. It also provides a Base connection. The model line "G1 3 5 N003 2 0.724m" sets the CTR and is the only difference between devices.

I also redid ALL the schematic symbols since I accidently mixed blue and black colors. 

![MOC207](https://user-images.githubusercontent.com/102838604/219436030-9741b973-69ab-44cf-aa20-0e3f85f7ff2b.jpg)

[Opto_Isolators_prj.zip](https://github.com/ra3xdh/qucs_s/files/10758519/Opto_Isolators_prj.zip)

**Comment by tomhajjar** [comment] 2023-02-22 15:37
Finally have a working Photovoltaic Isolator (PVI) model, the Avago ACPL-K30T. Guys at ngspice came up with the fix. 

They are making changes to ngspice so these modifications ultimately won't be required. 

ACPL-K30T.cir requires ngbehavior=ltpsa. 

ACPLK30T.cir will work without ngbehavior=ltpsa. 

https://sourceforge.net/p/ngspice/discussion/120973/thread/8c874eb3ec/

![ACPLK30T_DC](https://user-images.githubusercontent.com/102838604/220673279-fd84c029-b758-4e92-bab9-70597f61a384.jpg)

![ACPLK30T_TRAN](https://user-images.githubusercontent.com/102838604/220673321-d6329602-9086-4f6a-ab5e-b7158c5e21d0.jpg)

[ACPL-K30T_PVI.zip](https://github.com/ra3xdh/qucs_s/files/10805431/ACPL-K30T_PVI.zip)

**Comment by tomhajjar** [comment] 2023-02-22 16:37
I redid a number of components in the Opto Isolators project. 

4N25 and MOC207 NPN Optocouplers. MOC207 also models the base connection which is desirable. Neither require ngbehavior=ltps

BRT22H/M and MOC3082 Opto-Triacs. MOC3082 does not require ngbehavior=ltps

It would be good to document that subcircuit.sch file names CANNOT be the same as the subcircuit.cir file name. The error messages created by ngspice are confusing, masking what the real problem is. 

[Opto_Isolators_prj.zip](https://github.com/ra3xdh/qucs_s/files/10806046/Opto_Isolators_prj.zip)

**Comment by ra3xdh** [comment] 2023-10-24 13:46
I have added `Optocoupler.lib` library by the recent commit. This library will be available since the next release.

**Comment by ra3xdh** [comment] 2023-10-24 13:48
TRIACs and optothyristors need to be modified to ensure compatibility with Ngspice. Every occurrence of the `IF` statement should be replaced by ternary operator.  This will allow to use the library without the need to set the compatibility options for Ngspice.

**Comment by ra3xdh** [comment] 2023-10-24 13:50
Help is appreciated for this issue and #212. The C++ knowledge is not needed to modify the models.

**Comment by tomhajjar** [comment] 2023-10-25 01:29
On 2/15/23, you modified a MOC3082 Opto Triac Spice model done by Helmut Sennewald. Is it usable to make into a library device?

![2023-10-24_211821](https://github.com/ra3xdh/qucs_s/assets/102838604/90227a48-cb02-4d7d-9189-c0a2643c4a25)
![2023-10-24_211729](https://github.com/ra3xdh/qucs_s/assets/102838604/60f93cc7-4eb0-4cfc-bc1d-cafdd69762df)
![2023-10-24_211806](https://github.com/ra3xdh/qucs_s/assets/102838604/d6dbf6bd-6716-4e9e-b52d-c2288a0d2ed6)

[MOC3022_Opto_Triac_prj.zip](https://github.com/ra3xdh/qucs_s/files/13157285/MOC3022_Opto_Triac_prj.zip)

**Comment by tomhajjar** [comment] 2023-10-25 01:35
I dug up a very old 2N5568 Triac Spice model done by Intusoft. I haven't had a chance to test it...

[2N5568_Triac.zip](https://github.com/ra3xdh/qucs_s/files/13158344/2N5568_Triac.zip)

**Comment by ra3xdh** [comment] 2023-10-25 05:51
> On 2/15/23, you modified a MOC3082 Opto Triac Spice model done by Helmut Sennewald

Yes,  I will add this device ti the library.

> I dug up some old SCR and Triac Thyristor models that might be usable

I have checked the SPICE sources and found that these models don't contain LTspice/PSpice specific definitions. It could be accepted for Qucs-S library.

**Comment by ra3xdh** [comment] 2023-10-25 06:22
I have added MOC3082 model. The new `Optocoupler.lib` library will be available since the next version. Thyristor library will be provided in #212. Closing this ticket as completed.

**Closed** 2023-10-25 06:24 UTC
Labels: library

**Comment by tomhajjar** [comment] 2023-10-26 15:25
Is the ACPLK30T Photovoltaic Isolator usable in the optocoupler library? I realize I sent confusing and cluttered messages and files for this device. The device was modified by the ngspice guys to be compatible. 

![2023-10-26_112133](https://github.com/ra3xdh/qucs_s/assets/102838604/ce9111ac-09d9-4b90-bcc1-004f9f06d9f9)
![2023-10-26_112153](https://github.com/ra3xdh/qucs_s/assets/102838604/27ee141f-925d-4c9f-a585-9669dd6a15d2)

[Photo_Voltaic_Isolator_prj.zip](https://github.com/ra3xdh/qucs_s/files/13179454/Photo_Voltaic_Isolator_prj.zip)

**Comment by ra3xdh** [comment] 2023-10-26 15:27
I didn't include the ACPLK30T device. I will add it on the next library update.

**Comment by tomhajjar** [comment] 2023-12-05 14:51
Just confirming that the ACPLK30T Photo Voltaic Isolator will make it into the next release. It can be included in Optocoupler.lib if you don't want to make another library.

**Comment by tomhajjar** [comment] 2024-03-16 13:49
Confirming that the ACPL_K30T Photo Voltaic Isolator will make it into the next release. It can be included in Optocoupler.lib if you don't want to make another library.

I tested it recently in Trainline_Driver.sch. It needs a resistor load in the MegOhm range

[ACPL-K30T_PVI.zip](https://github.com/ra3xdh/qucs_s/files/14623748/ACPL-K30T_PVI.zip)
