### ISSUE TITLE
.INCLUDE SCRIPT and .GLOBAL PARAM cause Qucs-S to crash

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#574] opened 2024-02-16 23:23 UTC
See #569

**Comment by ra3xdh** [comment] 2024-02-17 05:39
I cannot reproduce the crash. The both devices work as expected on my machine.

**Comment by ra3xdh** [comment] 2024-03-08 08:44
Closing as cannot reproduce.

**Closed by ra3xdh** 2024-03-08 08:44 UTC
Labels: cannot reproduce
