### ISSUE TITLE
Schematic glitches fedora 37 [Qt6]

### ISSUE THREAD

**Issue by aviadb** [ra3xdh/qucs_s#227] opened 2023-02-20 18:00 UTC
In the schematic viewer,
moving parts or wires makes the wires to disappear until the component is released.

 
![215077901-7948cda4-bbdb-43e4-9e4a-ad628fac43ac](https://user-images.githubusercontent.com/13761044/220174543-76486a83-a275-4d44-93fd-142ce23cf4f9.gif)

Fedora 37, Qt6, KDE desktop with dark theme

**Comment by ra3xdh** [comment] 2023-02-20 18:47
It was already reported here https://github.com/ra3xdh/qucs_s/issues/190#issuecomment-1406371905 I remember about this issue, but unfortunately I cannot reproduce and debug it. I have tried Fedora installation into the VM and everything works as expected here. Physical installation of the Ubuntu22.04 with Qt6 also works as expected. I only may suspect this may be related to Wayland.

**Comment by cznwhale** [comment] 2023-02-20 18:54
The same behavior is on the raspberry pi version. (I use the September 22nd 2022 release, 32 bit version, Kernel: Linux 5.15.84-v7l+, on a 4B model)

**Comment by ra3xdh** [comment] 2023-02-21 05:09
The issue also may be fixed by https://github.com/ra3xdh/qucs_s/pull/214/commits/fe135fa8d45d649118ad6ce4934f781c6d8b9b55 Did you try compile the latest `current` branch?

**Comment by cznwhale** [comment] 2023-02-21 06:37
in my case (Raspberry Pi version) I used the precompiled binary (qucs-s_1.0.1-1_armhf.deb)

**Comment by cznwhale** [comment] 2023-02-21 06:41
I now realize that the same behavior is for Windows portable version (qucs_s_win64_1_0_1.zip)

**Comment by ra3xdh** [comment] 2023-02-21 07:22
I have just tested the Windows v1.0.1 package using the physical Windows installation (not VM) and also cannot reproduce the issue. Component dragging works as expected on my hardware. Therefore I cannot provide a fix, because I still cannot reproduce this bug.

**Comment by aviadb** [comment] 2023-02-21 17:40
Tried with the latest, problem still exists.
Any log dump that I can provide to help you in analyzing this behavior?

**Comment by ra3xdh** [comment] 2023-02-22 06:26
The information related to this problem is not logged by application. I suspect this may be hardware-dependent bug in Qt itself. Qt relies on OpenGL for the rendering and this may interact with the Wayland or graphic card driver in a weird way. The main problem is that I have tried different hardware including Nvidia, Radeon, and Intel and everything works as expected on my hardware. No issue observed with X11 and Windows. I still cannot reproduce this issue. And therefore I cannot provide a workaround. Contribution is highly welcome here. Currntly I can only speculate about its reason.  Also there may be something in the Qt configuration related to the rendering settings or scaling.

**Comment by ra3xdh** [comment] 2023-02-22 11:14
@aviadb You may try the fix proposed in #229 I didn't merge it into the `current` branch, you need to apply patch manually. I suspect these two issues may be related. I also cannot reproduce #229 on my hardware.

**Comment by aviadb** [comment] 2023-02-22 11:33
Hi @ra3xdh , thank you for your suggestion.

Tried to comment out this line:
![image](https://user-images.githubusercontent.com/13761044/220608365-5b14a867-769d-4c34-8715-33def817183f.png)

No success, the issue is still there.

**Comment by dsm** [comment] 2023-02-28 19:10
I tried fedora 37 with qt6 same issue is still there.

**Comment by ra3xdh** [comment] 2023-03-01 15:12
@dsm please consider providing a fix if you can reproduce this issue. I have tried different hardware and OS combinations including WIndows10 and 11 and still cannot reproduce it. The start point for debugger may be `Component::paintScheme()` method in `component.cpp`.

**Comment by dsm** [comment] 2023-03-01 19:08
I tried something but I cannot resolve symbols redraw every move but lines are not. maybe new lines coordinate not calculate while moving.

**Comment by dsm** [comment] 2023-03-03 08:12
windows 10 with qucs 1.0.1 and current branch with qt6 have the same issue 

![Animation](https://user-images.githubusercontent.com/41967334/222666628-45e9129c-56ea-4327-90b1-38ad7776e390.gif)

**Comment by dsm** [comment] 2023-03-03 12:29
if you move components using keyboard it's working. I didn't find any solution

![Animation](https://user-images.githubusercontent.com/41967334/222720094-adbebd79-95da-49b3-8944-0031f67862e0.gif)

**Comment by ra3xdh** [comment] 2023-03-03 12:50
> if you move components using keyboard it's working.

The moving of the component with keyboard doesn't invoke the `Component::paintScheme()` I guess this issue lies somewhere in in this method. I cannot provide you a more info because I cannot reproduce it on my hardware. 

> windows 10 with qucs 1.0.1 and current branch with qt6 have the same issue

It is not bug because of Qt5 migration and not related to this issue. I have just checked old Qt4 version and it also doesn't render wires while moving with mouse. But the component outline is rendered normally like on your screenshot.

**Comment by dsm** [comment] 2023-03-03 13:07
qt5 or qt6 build have same behaviour on my machine. I don't know it's qt related bug but if you not release mouse button while moving not update the wires maybe it's mouse action problem I cannot debug correctly. it's not important it's just an cosmetic bug. we will fix anytime

**Comment by ra3xdh** [comment] 2023-09-26 13:38
I still cannot reproduce this issue and provide debugging. @aviadb Could you try this patch for `schematic.cpp` and tell the result? This may fix the contour drawing.
~~~
diff --git a/qucs/schematic.cpp b/qucs/schematic.cpp
index 01fe40aa..41c883a1 100644
--- a/qucs/schematic.cpp
+++ b/qucs/schematic.cpp
@@ -462,7 +462,10 @@ void Schematic::drawContents(QPainter *p, int, int, int, int)
   {
     // QPainter painter2(viewport()); for if(p.PaintOnViewport)
     QPen pen(Qt::black);
-    Painter.Painter->setPen(Qt::black);
+    QPen pen1(Qt::black);
+    pen1.setWidth(1);
+    Painter.Painter->setPen(pen1);
+    //Painter.Painter->setPen(Qt::black);
     switch(p.pe)
     {
       case _NotRop:
~~~

**Comment by aviadb** [comment] 2023-11-22 09:48
@ra3xdh ,
The issue still persist with the suggested fix.
Using the arrow keys, I do not see the problem. Only when dragging elements with mouse.

**Comment by ra3xdh** [comment] 2024-01-18 13:22
#467 provides a fix for this issue. @aviadb , Could you test it, because I still cannot reproduce a bug with moving.

**Closed** 2024-01-19 16:36 UTC
Labels: help wanted, qt6, cannot reproduce

**Comment by aviadb** [comment] 2024-01-20 18:57
Thanks @ra3xdh, the provided solution fixes the problem.
