### ISSUE TITLE
Qucs-S misbehaving.... or is it ngspice....

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#447] opened 2024-01-09 21:33 UTC
This is in reference to #436. ngspice is unable to process Tlines as used as delay elements in TI "transient" Spice models. I wanted to see how ngspice handled Tline as used as delay elements.

Attached are 3 simple voltage delay line simulations using different Td parameters and Trans Sim times.

V_Delay.sch works as expected

V_Delay_2.sch output contains strange discontinuities. I'm unsure if this is a symptom of ngspice not handling Tlines delay elements properly.

V_Delay_3.sch creates a huge file V_Delay_3.dat.ngspice, causing Qucs-S to become unresponsive requiring Windows Task Manager to close. I realize the Trans Sim times for V_Delay_3.sch are excessive and create a huge file, but Qucs-S shouldn't freeze up. ngspice via DuSpice processed the netlist.

Attached are the project and netlists to test ngspice using DuSpice. All "work" but V_Delay_2.sch output still looks odd.

![2024-01-09_163519](https://github.com/ra3xdh/qucs_s/assets/102838604/00d2206b-7e1d-4e4c-a84f-10e776bc114a)

![2024-01-09_160930](https://github.com/ra3xdh/qucs_s/assets/102838604/463fbd29-8593-444f-86d4-ba1852792e56)

[Test_prj.zip](https://github.com/ra3xdh/qucs_s/files/13879220/Test_prj.zip)
[Delay Lines.zip](https://github.com/ra3xdh/qucs_s/files/13880686/Delay.Lines.zip)

**Comment by tomhajjar** [comment] 2024-01-10 00:46
Any attempt to open V_Delay_3.sch causes Qucs-S to become unresponsive.  This is after a reboot...

![2024-01-09_194503](https://github.com/ra3xdh/qucs_s/assets/102838604/717bc5f1-7fae-4be6-bba2-7098887558e2)

**Comment by ra3xdh** [comment] 2024-01-10 12:57
> V_Delay_2.sch output contains strange discontinuities

I cannot reproduce the discontinuities on my machine. Everything works as expected. Please check your Ngspice version. The discontinuities are surely not Qucs-S error. 

![image](https://github.com/ra3xdh/qucs_s/assets/4920080/28afb90f-f7cd-4054-88e5-3e69c1277437)

> V_Delay_3.sch creates a huge file V_Delay_3.dat.ngspice, causing Qucs-S to become unresponsive

Ngspice may adjust the time step automatically. You have the simulation duration 5ms and rise time of the pulsed source 1ns. Ngspice may decide to reduce time step to 1ns at some conditions and you will get around 5000000 points in dataset. Qucs-S tries to convert this huge dataset and may freeze. The huge dataset is not a normal simulation operation. I can add an option to ask user if the large dataset is detected. But it is not obvious how to distinguish "large" and "normal" size datasets.

**Comment by ra3xdh** [comment] 2024-01-10 13:13
>  Is there a "setting" that is causing Qucs-S to "choke" on the large file?

The XML dataset format used by Qucs-S has numerous design issues and doesn't support large data volumes. The switching to HDF5 https://docs.hdfgroup.org/hdf5/develop/_intro_h_d_f5.html may help. The HDF5 format is designed to support both large small data files. But I don't consider this to be done in the near future because of time constraints.

**Comment by tomhajjar** [comment] 2024-01-11 22:48
I tested the same circuit V_Delay_2.sch in LTSpice and it works as expected. 

LTSpice netlist was exported and ngspice again generated data with slightly different discontinuities. 

Still waiting for response over at ngspice...

![2024-01-11_154615](https://github.com/ra3xdh/qucs_s/assets/102838604/3b9ddfb8-2d39-4e19-a8ba-e1a2134ab4de)

![2024-01-11_154445](https://github.com/ra3xdh/qucs_s/assets/102838604/39b4aa2d-a669-4350-96a1-2af093de5441)

[Delay_line_netlists.zip](https://github.com/ra3xdh/qucs_s/files/13909132/Delay_line_netlists.zip)

**Comment by ra3xdh** [comment] 2024-01-12 05:53
I still cannot reproduce discontinuities using the Linux version. This may be something build specific. Closing the ticket as not related to Qucs-S GUI level.

**Closed by ra3xdh** 2024-01-12 05:53 UTC

**Comment by tomhajjar** [comment] 2024-01-12 12:59
Dietmar at ngspice has reproduced my data. Something changed between ngspice release 39 and 40.

https://sourceforge.net/p/ngspice/discussion/120973/thread/440b76e297/

![Bildschirmfoto vom 2024-01-12 08-37-49](https://github.com/ra3xdh/qucs_s/assets/102838604/2a4457da-ce8d-445a-9ab2-3844af53266b)

![Bildschirmfoto vom 2024-01-12 08-38-35](https://github.com/ra3xdh/qucs_s/assets/102838604/64cc3ad9-81c6-4db1-9c5a-62b8cd8e4038)

**Comment by tomhajjar** [comment] 2024-01-12 18:47
I compared releases ngspice 42-64 with ngspice 38-64 and the data is dramatically different.

The data using ngspice 38-64 has slight differences compared with LTSpice.

![ngspice_38](https://github.com/ra3xdh/qucs_s/assets/102838604/847066d9-c254-491c-8e2c-a0ab915eb555)
![ngspice_42](https://github.com/ra3xdh/qucs_s/assets/102838604/faf15404-b628-4eca-9b5e-821e7b500be3)
![2024-01-11_154615](https://github.com/ra3xdh/qucs_s/assets/102838604/16abbbc2-9798-43c2-bef1-67e88ecd3c03)
