### ISSUE TITLE
Thyristor testing (Triac, SCR, Diac and Sidac)

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#212] opened 2023-02-06 01:51 UTC
Having issues getting various Thyristor Spice models (Triac, SCR, Diac and Sidac) to work under Qucs-S. I have tested many in LTSpice and a few using ngspice. 

For example, AC_Dimmer_3.sch is tested under Qucs-S and KiCad, both using ngspice. I cannot get the Qucs-S simulation to agree with the KiCad one. 

TODO from @ra3xdh 

- [ ] Add library containing thyristor devices

![2023-02-05_203913](https://user-images.githubusercontent.com/102838604/216863540-0ac01b74-2ae1-4aff-a6e0-f300fc0d1a95.jpg)
![2023-02-05_203832](https://user-images.githubusercontent.com/102838604/216863561-b8e1daf2-b4a6-4193-8f7c-6a514ec9125c.jpg)

[Diac_Triac_SCR_prj.zip](https://github.com/ra3xdh/qucs_s/files/10636802/Diac_Triac_SCR_prj.zip)
[KiCad_Triac.zip](https://github.com/ra3xdh/qucs_s/files/10636804/KiCad_Triac.zip)

**Comment by ra3xdh** [comment] 2023-02-06 05:59
The KiCAD and Qucs-S uses different Ngspice version. KiCAD uses Ngspice as the shared library (DLL or SO module), but Qucs-S uses Ngspice as the standalone application. My version of KiCAD using Ngspice-36 shared library cannot run your schematic even using "LTspice compatibility mode". It tells me `if no such function` error. I think the difference between two Ngspice versions may be explained LTspice compatibility mode implementation that was improved in the recent versions. 

Adding a thyristor devices library for Qucs-S is a good idea. I have updated TODO list. Your project containing thyristor models could be used as the starting point. But the models need to be rewritten to get rid of LTspice constructions like `if` operator which is not implemented in Ngspice. Always using LTspice compatibility mode to simulate schematics using one specific library is not a good idea.

**Comment by tomhajjar** [comment] 2023-02-06 14:43
I used ngspice 38 via DuSpice and confirmed Triac_Dimmer.cir works the same as in KiCad. No idea why it fails under Qucs-S.

Triac_Dimmer.log indicates a number of warnings and unrecognized parameters but the simulation finishes.

![2023-02-06_094010](https://user-images.githubusercontent.com/102838604/217001607-ef3f1331-1772-4426-8b7a-7c41e9d1c1f9.jpg)

![2023-02-06_093105](https://user-images.githubusercontent.com/102838604/217000446-479bac7e-4a39-4aa4-99b6-54b7accf246d.jpg)

[KiCad_Triac.zip](https://github.com/ra3xdh/qucs_s/files/10664107/KiCad_Triac.zip)

**Comment by ra3xdh** [comment] 2023-02-06 14:47
I need the `Triac_dimmer.cir` that was used standalone run with DuSpice. I need to compare netlist this Qucs-S and netlist from KiCAD line by line.

**Comment by tomhajjar** [comment] 2023-02-06 14:49
Ooops. I sent the wrong file. 
[Thyristors.zip](https://github.com/ra3xdh/qucs_s/files/10664219/Thyristors.zip)

**Comment by ra3xdh** [comment] 2023-02-06 15:05
I made some investigations and found that it is again not a bug in Qucs-S. You have different AC source parameters and TRAN simulation settings in manually generated netlist and Qucs schematic. After applying the correction I obtained identical result. See the attached screenshot.
![image](https://user-images.githubusercontent.com/4920080/217007239-72ea147e-e2f8-4557-824a-68d0ca9fb41a.png)

**Comment by tomhajjar** [comment] 2023-02-07 02:05
Fixed the simulations. The various models seem to function. Triac, SCR, Diac and Sidac. 

Sidac is a newer type of Diac used for surge protection. It can handle far more power than a Diac. Many more Sidac's are sold each year than Diac's. 

Shockley or 4-layer diodes haven't been sold in decades. Diac/Sidac are effectively two Shockley diodes in anti-parallel. 

[Diac_Triac_SCR_prj.zip](https://github.com/ra3xdh/qucs_s/files/10670755/Diac_Triac_SCR_prj.zip)

**Comment by tomhajjar** [comment] 2023-10-25 15:58
I redid the models for a DB3 Diac, L6008L6 Triac and S8020L SCR . They should do the job.

![2023-10-25_114206](https://github.com/ra3xdh/qucs_s/assets/102838604/82ff81dc-e443-4cb3-ac97-3a1dcfa42d44)
![2023-10-25_114253](https://github.com/ra3xdh/qucs_s/assets/102838604/4d1a00b8-a8d9-4fc9-9367-9baf9126b348)
![2023-10-25_114219](https://github.com/ra3xdh/qucs_s/assets/102838604/9435169b-87c2-4b91-906c-48b0ff5b7bed)

![2023-10-25_115546](https://github.com/ra3xdh/qucs_s/assets/102838604/d6d76dda-8cf8-4bae-84d6-56013ec24dbe)

[Diac_Triac_SCR.zip](https://github.com/ra3xdh/qucs_s/files/13168063/Diac_Triac_SCR.zip)

**Comment by ra3xdh** [comment] 2023-10-26 06:43
I have uploaded `Thyristor.lib` library containing diac, SCR, and Triac devices. This library will be available since the next release. Closing ticket as completed.

**Closed by ra3xdh** 2023-10-26 06:43 UTC
Labels: help wanted, library
