### ISSUE TITLE
Update "broke" XYCE Digital Library

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#1163] opened 2024-12-29 17:42 UTC
Update "broke" XYCE Digital Library so the example project doesn't work anymore. The .params and variables in the Library seem to be the issue.

Not that anyone used it but was the change by design?

**Comment by ra3xdh** [comment] 2024-12-29 17:44
Could you provide a link to the broken schematic? I didn't test the XyceDigital for a long time. I suspect this may be broken earlier.

**Comment by tomhajjar** [comment] 2024-12-29 17:47
My mistake... I wasn't in xyce mode... Delete...

I was looking for a behavioral buffer to use as a digital delay element. I haven't found one that allows vcc and delay to be varied...

**Comment by ra3xdh** [comment] 2024-12-29 17:48
Closing as not a bug.

**Closed by ra3xdh** 2024-12-29 17:48 UTC
Labels: xyce, not a bug
