### ISSUE TITLE
Simulation of S-Parameter File: 

### ISSUE THREAD

**Issue by 3813127458** [ra3xdh/qucs_s#552] opened 2024-02-11 06:02 UTC
Issue: Simulation of S-parameter (S2P) files does not work.

Error Message: 
```
Error on line:
  a.xx1.a11 %vd xx1.10 0 %vd xx1.11 xx1.12 xx1:xfer1
 MIF-ERROR - unable to find definition of model xx1:xfer1
    Simulation interrupted due to error!
```
[Archive.zip](https://github.com/ra3xdh/qucs_s/files/14231408/Archive.zip)

The schematic shown in the screenshot below forces S-parameter simulation in the frequency domain and transient simulation in the time domain simultaneously. 
Transient simulation is probably not supported by the ngspice PWL transfer function (Spice model name: `xfer`) yet.
However, AC (S-parameter) simulation should work.

Finally, transient and S-parameter simulation of Touchstone SPx files should work simultaneously in the frequency and time domain. Maybe, to be investigated and discussed with the ngspice team.

![image](https://github.com/ra3xdh/qucs_s/assets/75557552/9d4d2baa-0544-4e75-b36b-a3a17245fc1f)

**Comment by ra3xdh** [comment] 2024-02-11 06:30
> Maybe, to be investigated and discussed with the ngspice team.

Closing because it is not Qucs-S error. Please provide a minimal netlist reproducing this problem and report to Ngspice forum.

**Closed by ra3xdh** 2024-02-11 06:30 UTC
