### ISSUE TITLE
Quc-S is inserting ".PARAM Export = no" into the netlist

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#1105] opened 2024-11-30 17:59 UTC
I don't see this happening in all the other cases of using ".PARAM" in a schematic but Quc-S is inserting ".PARAM Export = no" into this "XSPICE" netlist causing ngspice to flag it as an error and halting.

I'm looking into using XSPICE for "Systems Analysis" and wanted to reproduce the ngspice XSPICE PLL example. Unfortunately this issue popped up.

For this specific case, "Phase_Freq_Det_test.sch" I'm trying to make a schematic of "test-f-p-det.cir" and trying to understand why Holger's netlist it is so "complex". It has digital zero, digital one, d to a for plotting...etc. Does XSPICE digital really require all this extra "support" in a netlist?

![2024-11-30_124205](https://github.com/user-attachments/assets/d4059721-c768-4dbb-8720-5f0f0f63117d)
![2024-11-30_124236](https://github.com/user-attachments/assets/14827d37-a1b0-4b5a-bb3d-f401e622f710)
![2024-11-30_124133](https://github.com/user-attachments/assets/5422ea7e-a8e5-4f14-b58c-a0752e414716)

[XSPICE_PLL_prj.zip](https://github.com/user-attachments/files/17966338/XSPICE_PLL_prj.zip)

**Comment by ra3xdh** [comment] 2024-11-30 18:07
@tomhajjar  Remove the "Put result in dataset" checkbox in the `.PARAM` properties dialog and everything will work as expected. This checkbox may be easily set by mistake.

![image](https://github.com/user-attachments/assets/4eae1d30-59af-4844-903d-0fd4043056c3)


@iwbnwif  Please have a look at this. The *Put result in dataset* should not be enabled only for Qucs equations. The .PARAM is never put in the dataset. And Nutmeg equations is always put in the dataset. SPICE handles the both automatically and there is no way to control this manually. The *Put result in dataset* is Qucsator only feature.

**Comment by tomhajjar** [comment] 2024-11-30 18:13
It was never checked. I tried checking and un-checking and the same result.

Like I mentioned this isn't an issue on all the other "digital" projects I have using .PARAM VCC=xx. It's unique to this schematic.

![2024-11-30_131003](https://github.com/user-attachments/assets/ee131f53-d8c1-4142-8c50-d35fffecd3fb)

**Comment by ra3xdh** [comment] 2024-11-30 18:16
> It was never checked. I tried checking and un-checking and the same result.

I cannot reproduce this with my schematics. The error appears only if this checkbox is checked. Need further investigations.

**Comment by tomhajjar** [comment] 2024-11-30 18:18
What about the project I sent?

**Comment by ra3xdh** [comment] 2024-11-30 18:23
Yes, i can reproduce it. I have found that the `.PARAM` has extra `Export` property in the XML schematic file. This made the schematic broken. Please wait for fix.

**Comment by iwbnwif** [comment] 2024-11-30 18:45
> The Put result in dataset should not be enabled only for Qucs equations. 

Please can I check if this should say "should be enabled only for Qucs equations"?

I.e., no other forms of equations even need this checkbox

**Comment by ra3xdh** [comment] 2024-11-30 18:47
> Please can I check if this should say "should be enabled only for Qucs equations"?

Yes, this is a typo. This option should present only for Qucs equations.

**Comment by tomhajjar** [comment] 2024-11-30 18:49
How is it the schematic line format changed?

Old:
<SpicePar SpicePar1 1 60 350 -28 16 0 0 "vcc=5" 1>

New:
<SpicePar SpicePar1 1 20 250 -28 16 0 0 "vcc=5" 1 "Export=no" 0>

**Comment by ra3xdh** [comment] 2024-11-30 18:50
> How is it the schematic line format changed?

This is a bug. The *SpicePar* should not contain *Export* property.

**Comment by tomhajjar** [comment] 2024-11-30 18:53
Editing the schematic with a text editor is a short term solution that works.

**Comment by iwbnwif** [comment] 2024-11-30 21:59
@tomhajjar thank you for spotting this. I have put in a PR to hopefully fix this problem.

The line `export = no` might appear in the parameter list if you open a file that was created with this bug. However, you can freely delete the line everything should be okay from then on.

Please let me know if you find any other problems or this doesn't fix it.

**Comment by iwbnwif** [comment] 2024-11-30 22:05
@tomhajjar sorry slightly OT but when I run the simulation in your project the ngspice result set does not match with the graphs. I've noticed this with quite a few of the examples that you provide.

For example, I have no d_clk or d_out1 results, and I am wondering why that is?

![image](https://github.com/user-attachments/assets/e9cbf8fd-83de-4361-8694-c905d65c6129)

**Comment by tomhajjar** [comment] 2024-11-30 22:18
I noticed this as well. There is always one missing vector. Many times I don't plot the vector and don't know it's missing.
In this one case it was "fixed" by adding a "dummy" line "dR = R+0". 

Now if I could only get my various phase-frequency detectors to work...

![2024-11-30_171041](https://github.com/user-attachments/assets/9b11fb2a-4d0d-4227-9c96-62f7190401e1)

[PLL_CMOS_prj.zip](https://github.com/user-attachments/files/17967172/PLL_CMOS_prj.zip)

**Comment by iwbnwif** [comment] 2024-11-30 22:25
> Now if I could only get my various phase-frequency detectors to work...

Good luck! It's very useful that you are giving the new dialog a good workout. I hope it makes inputting and editing equations a little bit easier.

**Comment by ra3xdh** [comment] 2024-12-01 07:47
Fixed by #1106

**Closed** 2024-12-01 07:47 UTC
Labels: bug
