### ISSUE TITLE
Multiple issues trying to port Qucs project to Qucs-S

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#173] opened 2022-10-27 14:38 UTC
I ran into many problems trying to port a Qucs current mirror project over to Qucs-S. My comments are for current_mirror_bjt.sch but the same problems exist for all the files. 

If a voltage/current probe is added to T2 collector, i(v1) and i(v2) currents and net voltages become unavailable for plots. 

If a net Vct2 is added to T2 collector, i(v1) and i(v2) currents and net voltages become unavailable for plots. 

Deactivating a voltage/current probe doesn't work. I have to delete them to get net voltages and currents to re-appear. 

Why can't I add voltage/current probe or net name to a source like V1 or V2 without ngspice giving an error?

I have tried every variation using the Nutmeg deriv function to replace the Qucs diff function to calculate Rout without success. I am missing something. The file mirrorbip_mod.sch shows my attempts. 

![2022-10-27_101606](https://user-images.githubusercontent.com/102838604/198312466-968a86ff-efbb-414d-96da-85b75d086305.jpg)
![2022-10-27_101642](https://user-images.githubusercontent.com/102838604/198312475-1b6efdf2-af80-4010-962b-592c2740517d.jpg)
![2022-10-27_101736](https://user-images.githubusercontent.com/102838604/198312477-ca25ac83-2c1f-4d9a-9b8e-acb0d3a557b3.jpg)
![2022-10-27_110349](https://user-images.githubusercontent.com/102838604/198326984-08157852-2a9c-4b7d-a754-6415f0f4a457.jpg)

[Mirrors_prj.zip](https://github.com/ra3xdh/qucs_s/files/9880264/Mirrors_prj.zip)

**Comment by tomhajjar** [comment] 2022-10-27 14:40
Qucs current mirror variations files I recently edited.

[Mirrors_Qucs_prj.zip](https://github.com/ra3xdh/qucs_s/files/9880413/Mirrors_Qucs_prj.zip)

**Comment by ra3xdh** [comment] 2022-10-27 15:57
Hello Tom,

here are some explanations 
> If a voltage/current probe is added to T2 collector, i(v1) and i(v2) currents and net voltages become unavailable for plots.

You rely on undefined behavior in this simulation. The implicit names are used in the plot. If no named nodes specified in the schematic, the auto-generated `write` statement in the netlist will write **all** nodes to the dataset. If you add the voltage probe here, the dataset will contain only named nodes and probes. Probably disabling the probe doesn't work properly here. The solution is always name nodes explicitly with *Insert->Wire label* or add explicit probe and rely only on named nodes and probe variables in the equations to avoid such issues. 

> I have tried every variation using the Nutmeg deriv function to replace the Qucs diff function to calculate Rout without success.

There is no direct replacement for Qucs `diff()` function in Ngspice. You need to use a construction with `vecd()` function instead to get the `dV/dI` vector. See attached screenshot.

 
![image](https://user-images.githubusercontent.com/4920080/198339827-fa5cab6c-2a3b-41cc-85e1-9c23ee6cc42c.png)

**Comment by tomhajjar** [comment] 2022-10-27 17:33
I added Ic1, Ic2 and flipped direction. What Ro calculation do you think is correct? They don't match.

![2022-10-27_131644](https://user-images.githubusercontent.com/102838604/198358885-6ec286ab-9ad3-4c53-ae61-ff966dd3b595.jpg)
![2022-10-27_133040](https://user-images.githubusercontent.com/102838604/198358892-4bab06b9-0372-4a2e-b6f5-914dbccd3b3f.jpg)

[Mirrorbip.zip](https://github.com/ra3xdh/qucs_s/files/9881805/Mirrorbip.zip)

**Comment by tomhajjar** [comment] 2022-10-27 21:47
When I opened the identical sch and dat files generated by Qucs in Qucs-S, the plot of Rout in Qucs-S is scaled differently. I have not done any simulation in Qucs-S, I just opened the file. Notice the Equation files are the same. I have not edited this file to work with ngspice. Why would Rout be scaled differently when the two drain currents are scaled properly?

![2022-10-27_173633](https://user-images.githubusercontent.com/102838604/198403422-b55a26c3-3e19-447c-b6a2-460df354f372.jpg)
![2022-10-27_173645](https://user-images.githubusercontent.com/102838604/198403425-9c1842da-df94-4627-b867-490e6366632a.jpg)

**Comment by ra3xdh** [comment] 2022-10-28 16:55
> When I opened the identical sch and dat files generated by Qucs in Qucs-S, the plot of Rout in Qucs-S is scaled differently

I cannot reproduce this bug on Linux platform. The values for Ron are identical for both Qucs and Qucs-S. Inspecting the `dat` file I can see the value for `Ron` approx. `1e14`. The Qucs-0.0.20 reads the dataset wrong.  So, this problem is not related to Qucs-S. Maybe this bug appears because the Qt4 library is deprecated and may operate wrong on modern platforms.   

![image](https://user-images.githubusercontent.com/4920080/198691093-b82743de-c89a-49b4-8f11-7c5e843e565a.png)

**Comment by ra3xdh** [comment] 2022-10-28 17:01
> What Ro calculation do you think is correct?

I have tested the Ngspice approach with the diode series resistance. The equation `vecd(v)/vecd(i)` gives the correct result for forward resistance. 

![image](https://user-images.githubusercontent.com/4920080/198692193-93b110d3-f0c6-4414-bf1c-ebd78d4460a1.png)

**Comment by ra3xdh** [comment] 2022-11-25 17:02
Assume the questions raised during the porting Qucs schematics to Qucs-S has been resolved. Closing the ticket.

**Closed by ra3xdh** 2022-11-25 17:02 UTC
